version: '3.8'

services:
  mysql:
    image: mariadb:10
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      TZ: Asia/Seoul
      MARIADB_DATABASE: pureureum
      MARIADB_USER: root
      MARIADB_PASSWORD: 1234
      MARIADB_ROOT_PASSWORD: 1234

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
