spring:
  profiles:
    include:
      - sentry
      - database
      - flyway
      - open-search
      - springdoc

server:
  error:
    whitelabel:
      enabled: false
  shutdown: graceful # rolling update를 위해 graceful shutdown을 사용한다.
